### ISSUE TITLE
SHA1 differs

### ISSUE THREAD

**Issue by einsteinsfool** [fyookball/keys-n-hashes#1]
Hello.

The SHA1 checksum differs in my situation. Could you confirm that the one in your repo is the latest one?
Or even better, can you change the SHA1 to SHA2? SHA1 is not safe as you can read [here](https://en.wikipedia.org/wiki/SHA1#Attacks).

What I ran was:
```
$ sha1sum Electron-Cash-2.9.0.tar.gz 
53391d5e824ee221e59a2636635063903a333d16  Electron-Cash-2.9.0.tar.gz
```

**Comment by ferminako** [comment]
me too sha1sum Electron-Cash-2.9.0.tar.gz
53391d5e824ee221e59a2636635063903a333d16  Electron-Cash-2.9.0.tar.gz

**Comment by fyookball** [comment]
sorry i had the wrong link on the site where the linux link incorrectly linked to mac file. refresh site and try again.

**Comment by ferminako** [comment]
Btw, as soon as I launch the wallet for first time is asking me for my wallet, but I didnot create any one before. So ?

Thanks

**Comment by ferminako** [comment]
I meant my wallet pasaword

**Comment by fyookball** [comment]
if you didnt have a wallet before then it should start by asking you what kind of wallet you want to create and then giving you a seed.  after that you can set a pwd if you want

**Comment by einsteinsfool** [comment]
What about providing SHA2 instead of SHA1? :-)

**Comment by fyookball** [comment]
i may decide to also upload SHA2 sums.  good suggestion.
