### ISSUE TITLE
Hashes not signed

### ISSUE THREAD

**Issue by Y2PM** [fyookball/keys-n-hashes#11]
The hashes are not signed, you have signatures separate from the hash values, you're meant to generate a hash value then sign it so the signature is part of the hash value. Otherwise we can't verify the hash value is legitimate. 

Here's an example: 

-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

Verify:
- - - https://keybase.io/jprichardson/pgp_keys.asc?fingerprint=12408650e2192febe4e7024c9d959455325b781a
- - - https://keybase.io/jprichardson

SHA256:

3f38984734b03e15a5659d7332ed2e068d349f195ef8f1b96447a4fa3b66d25f Exodus-linux-x64-1.32.0.zip
70c907046fceadcca17038427cbb5cf5262e8014f8cf9d07612648a062d931bb Exodus-macos-1.32.0.dmg
fdd2fc8a4840825601951e2764530f46195cc334e8de597d4d9f838df47804c9 Exodus-windows-x64-1.32.0.exe
c6b1a6291b5a347ddc6f0697435be359550bdeddf7eaa0487f0f6b6a28d81766 Exodus-windows-x64-1.32.0.nupkg

-----BEGIN PGP SIGNATURE-----

wsFcBAEBCAAQBQJZlj5qCRCdlZRVMlt4GgAAAG0QANR87v1upFVkNxLW4OYoTDWI
znn+uDFYJyVZDHhDzlTbEiNHfcLV0uOLVuIQoAQ1S4Ny+kjUJnr/xUTkW3Qxo6an
T/I3X89WPAI2xyb2263PJIcil507yL4+emyvDLkZU8nlIbd5mKHyKhnxrgjakdjn
Okk2nStlgjSeMQWzpniW3Ri5r8GwLoPR3daazUUYh3edhLKEpetQ9izOs9h38IBx
9oA8gWy4ljdfqtQT4XmvCiuHGp+0jf3uwMH8oE9uG7mHcFJlQLCbar9BfUTHemsK
104wMqyFhzo5JDPh1fRqB1Al+AwEBpY21Q6x7XtLejBShPR81H5Qz/Hmj9mU4A7p
1xn+naonw/o/VdpzRyfRQCz71KPvXQdKi4GiD2Vv9eTfTumViCtFXX9f9Ne0S8lD
EGJKa2Jnbs8WNZvU1882GMC2QyhO9crd82q32m23TuQ9LuxohxB83DMxB31oqNcj
NNmtdJEPBeVURtcaMPeZ6jZpaV4NDorj71vrZa4eflo6gQ63YNlNJvAYzBUb5RZX
b+amSHEevrAeuBVf4csD3rjsWnpWWSnxM53oZUxsUrO49svjubBWJVEX6FiyFUeG
CsRE8TWUL6Uo+gFX6E1Ul024MC4v6iM9IpeKBAv8qINq0kTmJq9I5S3Pbhb5hIl8
t89Nhk7/wUqbOWawjfG4
=J9UJ
-----END PGP SIGNATURE-----

**Comment by fyookball** [comment]
Thanks for the suggestion.  Will consider it for the future.
