### ISSUE TITLE
import paper wallet

### ISSUE THREAD

**Issue by owain82220** [fyookball/keys-n-hashes#12]
Trying to import a paper wallet. I'm getting stuck when I input the private key, it doesn't allow me to click the 'next' button.

These are the steps I'm taking up until that point:

File - New/Restore

Wallet - Standard Wallet

Use public or Private keys

Any ideas? Im pretty sure I've downloaded the latest version (Windows)

**Comment by fyookball** [comment]
wrong repo ... please use:

https://github.com/fyookball/electrum/issues
