### ISSUE TITLE
sha256sum ElectronCash-3.0.tar.gz

### ISSUE THREAD

**Issue by brakab** [fyookball/keys-n-hashes#16]
I'm receiving a different sha256sum when checking the linux tar download from the site. It doesn't match the SHA256.ElectronCash-3.0.tar.gz.txt checksum.

**Comment by fyookball** [comment]
hmm i will check it soon. in the meantime you can just download from github and run the setup commands from the readme.

**Comment by brakab** [comment]
I installed it in Windows and I can't send BCH. It reads: Invalid lines found Line #1: (BCH ADDRESS)

**Comment by brakab** [comment]
http://prntscr.com/hnhvfg

I copy and paste the BitPay address.

**Comment by brakab** [comment]
BCH address: CTzuQY5AWV3ynUDD3pgZtrhFBbcVcArdma

**Comment by fyookball** [comment]
did you clone master branch?

**Comment by fyookball** [comment]
will be fixed in 3.1
