### ISSUE TITLE
Would be great if you post the md5 for windows users.

### ISSUE THREAD

**Issue by bmjjr** [fyookball/keys-n-hashes#17]
Windows utility FVIC is simple to install and has output for md5 or sha1.  For sha256, we're looking at PowerShell scripts, taking things up a whole new level here. 

Would be great if you can include the md5.

**Comment by bmjjr** [comment]
PowerShell inputs for googlers:
Get-FileHash -Path <your file path here> -Algorithm SHA256

**Comment by b-f-** [comment]
Hmm

![image](https://user-images.githubusercontent.com/2358754/34765569-2e4e53cc-f5f2-11e7-9fb2-33817ac9ca8a.png)

**Comment by fyookball** [comment]
i will consider it.  i dont want to put too much burden with a million hashes, also could be confusing. have you seen the 7-zip utility for windows?  it includes sha256
