### ISSUE TITLE
SHA does not match

### ISSUE THREAD

**Issue by NeutralName** [fyookball/keys-n-hashes#18]
Hello:
I downloaded: 
ElectronCash-3.1.1.exe
and:  
SHA256.ElectronCash-3.1.1.exe.txt

2 things:
-the SHA does not look like a SHA
-Unsurprisingly, it does not match

please see screenshot: https://imgur.com/a/Fd5hw

please advise

**Comment by fyookball** [comment]
these are SHA256 , no longer sha1
