### ISSUE TITLE
Electron Cash cannot sign transaction

### ISSUE THREAD

**Issue by targon** [fyookball/keys-n-hashes#3]
I am trying to sign a transaction on my offline computer by using Tools > Load transaction.
When I click "sign", and after I entered my wallet password, I get an error dialog showing only the word "value".

I traced this down to lib/transaction.py Transaction.serialize_preimage:

    def serialize_preimage(self, i):
        nVersion = int_to_hex(self.version, 4)
        nHashType = int_to_hex(self.nHashType(), 4)
        nLocktime = int_to_hex(self.locktime, 4)
        inputs = self.inputs()
        outputs = self.outputs()
        txin = inputs[i]
        if True or self.is_segwit_input(txin): <---- Why is this hardcoded to True?
            hashPrevouts = Hash(''.join(self.serialize_outpoint(txin) for txin in inputs).decode('hex')).encode('hex')
            hashSequence = Hash(''.join(int_to_hex(txin.get('sequence', 0xffffffff - 1), 4) for txin in inputs).decode('hex')).encode('hex')
            hashOutputs = Hash(''.join(self.serialize_output(o) for o in outputs).decode('hex')).encode('hex')
            outpoint = self.serialize_outpoint(txin)
            scriptCode = push_script(self.get_preimage_script(txin))
            amount = int_to_hex(txin['value'], 8) <---- Here it fails because txin doesn't have 'value'
            nSequence = int_to_hex(txin.get('sequence', 0xffffffff - 1), 4)

**Comment by fyookball** [comment]
i'll look into trying to do an offline tx... serialization (SIGHASH FORKID) is required for BCC

**Comment by fyookball** [comment]
i was able to recreate this. thanks!

**Comment by fyookball** [comment]
this won't be fixed immediately.  comments from Kyuupichan:


loading is broken full stop.  It’s why multisig doesn’t work.  See the release notes. Fixing it is invasive, so I’ve not bothered so far.  It’s broken for segwit for the same reason - so much for Electrum being “Segwit enabled”.  It's got a heckuva lot more work to do there. It’s not trivial.  I suggest you try and change it so the whole TX info is saved as a dictionary in python format.  It tried to save stuff in some kind of electrum-specific hack of the native bitcoin format, and then added kludges over time to support multisig, segwit and everything else.  Best to chunk the lot and just do it properly.  However it will not be easy; just warning you.

**Comment by fyookball** [comment]
this also reported here https://github.com/fyookball/electrum/issues/7

So i will close this as duplicate. thanks for reporting and the info.
