### ISSUE TITLE
SHA1 not verifying.

### ISSUE THREAD

**Issue by hello1232** [fyookball/keys-n-hashes#5]
FILE CHECKSUM FCIV.exe 
i verify Electron-Cash-2.9.0.exe for windows and i get a11fe82c3daf563ae06a1d8b09e3ff4a   as a result.

https://github.com/fyookball/keys-n-hashes/blob/master/sigs-and-sums/win-linux/SHA1.Electron-Cash-2.9.0.exe.txt  says it should be  8daba1e5ddd4bf0721cc885c3575b65e21a185f0 Electron-Cash-2.9.0.exe

please fix

**Comment by hello1232** [comment]
Big warning on the main website do your file check. I do my checks and all the checks I do are different, I tried to download the file from different IP,s  all same result...

**Comment by fyookball** [comment]
I get 85f0 when i verify.

**Comment by hello1232** [comment]
So how is that possible? how can I send you the proof I get a11fe82c3daf563ae06a1d8b09e3ff4a
