### ISSUE TITLE
Virus

### ISSUE THREAD

**Issue by bom64** [fyookball/keys-n-hashes#9]
https://www.virustotal.com/en/file/000063885565e062c8130c316381b2856f74cc04051762973fbe5200a0e84672/analysis/

show:

Baidu	Win32.Trojan.WisdomEyes.16070401.9500.9974	20170803
WhiteArmor	Malware.HighConfidence	20170731

**Comment by fyookball** [comment]
what do you suggest? is there a process to submit saftey?

**Comment by bom64** [comment]
I have no other suggestion.

**Comment by fyookball** [comment]
seems good 2/64

**Comment by bom64** [comment]
No - only 0/64 is good for this type of apps.
